version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: bank_card_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bank_card_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: bank_card_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bank_card_db?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    volumes:
      - .:/app

volumes:
  mysql_data: